-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.category
(
    id character varying(16) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    last_update timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT category_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.category
    IS 'Category descriptions';

COMMENT ON COLUMN public.category.last_user
    IS 'Last username updated the ROW';

CREATE TABLE IF NOT EXISTS public.customer
(
    id smallserial NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Address" text COLLATE pg_catalog."default",
    "Active" boolean DEFAULT false,
    last_update timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    create_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT customer_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.customer
    IS 'Table of customers';

COMMENT ON COLUMN public.customer.create_date
    IS 'Date of entry';

CREATE TABLE IF NOT EXISTS public.demopool
(
    id character varying(64) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    for_sale boolean DEFAULT false,
    last_update timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT demopool_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.demopool
    IS 'Demo pools';

CREATE TABLE IF NOT EXISTS public.employee
(
    person_id integer NOT NULL,
    customer_id integer NOT NULL,
    title character varying(128) COLLATE pg_catalog."default",
    status boolean DEFAULT true,
    email character varying(128) COLLATE pg_catalog."default",
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Person" PRIMARY KEY (person_id, customer_id)
);

COMMENT ON TABLE public.employee
    IS 'Employee Customer relationship table';

CREATE TABLE IF NOT EXISTS public.help
(
    page character varying(64) COLLATE pg_catalog."default" NOT NULL,
    help_entry text COLLATE pg_catalog."default",
    last_update timestamp with time zone,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT help_pkey PRIMARY KEY (page)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    id bigserial NOT NULL,
    "ProductNo" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "SerialNo" character varying(16) COLLATE pg_catalog."default",
    "Available" boolean NOT NULL DEFAULT true,
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "DemoPool" character varying(64) COLLATE pg_catalog."default",
    transaction_id bigint,
    notes character varying(256) COLLATE pg_catalog."default",
    selectium_asset integer,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT inventory_pkey PRIMARY KEY (id),
    CONSTRAINT "Selectium Asset Number" UNIQUE (selectium_asset),
    CONSTRAINT "Serial Number" UNIQUE ("ProductNo", "SerialNo")
);

COMMENT ON TABLE public.inventory
    IS 'Table of all inventory items';

COMMENT ON COLUMN public.inventory."DemoPool"
    IS 'Selected demo pool';

COMMENT ON COLUMN public.inventory.notes
    IS 'inventory notes';

COMMENT ON CONSTRAINT "Selectium Asset Number" ON public.inventory
    IS 'Selectium Asset No in unique. Nulls are ignored';
COMMENT ON CONSTRAINT "Serial Number" ON public.inventory
    IS 'Serial Number is Unique in ProductNo/SerialNo combination';

CREATE TABLE IF NOT EXISTS public.person
(
    id smallserial NOT NULL,
    "Name" text COLLATE pg_catalog."default",
    "Email" text COLLATE pg_catalog."default",
    "Phone" character varying(16) COLLATE pg_catalog."default",
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT person_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.person
    IS 'Table of persons';

CREATE TABLE IF NOT EXISTS public.products
(
    "ProductNo" character varying(16) COLLATE pg_catalog."default" NOT NULL,
    "Description" character varying(128) COLLATE pg_catalog."default",
    "LongDescription" character varying(512) COLLATE pg_catalog."default",
    last_update timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "Category" character varying(16) COLLATE pg_catalog."default",
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT products_pkey PRIMARY KEY ("ProductNo")
);

COMMENT ON TABLE public.products
    IS 'Database for products in the inventory';

COMMENT ON COLUMN public.products."Category"
    IS 'Category of the product';

CREATE TABLE IF NOT EXISTS public.reverzi
(
    customer_id integer,
    customer_person_id integer,
    person_id integer,
    description text COLLATE pg_catalog."default",
    demo_start_date date,
    demo_end_date date,
    demo_return_date date,
    active boolean,
    demo_result text COLLATE pg_catalog."default",
    last_update timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id bigserial NOT NULL,
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT "Reverz Header" PRIMARY KEY (id)
);

COMMENT ON TABLE public.reverzi
    IS 'Reverz header. Master record for each reverz. ';

COMMENT ON COLUMN public.reverzi.id
    IS 'Reverz ID';

CREATE TABLE IF NOT EXISTS public.transactions
(
    id bigserial NOT NULL,
    inventory_id bigint NOT NULL,
    active boolean,
    demo_start_date date NOT NULL,
    demo_end_date date,
    last_update timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    loan_reason text COLLATE pg_catalog."default",
    demo_return_date date,
    reverz_id integer,
    notes character varying(1024) COLLATE pg_catalog."default",
    last_user character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

COMMENT ON TABLE public.transactions
    IS 'Table of demo loan transactions';

COMMENT ON COLUMN public.transactions.demo_return_date
    IS 'Equipment real return date';

COMMENT ON COLUMN public.transactions.reverz_id
    IS 'Reverz number';

COMMENT ON COLUMN public.transactions.notes
    IS 'Inventory notes';

ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT "Customer_id" FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.employee
    ADD CONSTRAINT "Person_id" FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Person_id"
    ON public.employee(person_id);


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT "Active Transaction" FOREIGN KEY (transaction_id)
    REFERENCES public.transactions (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE;
CREATE INDEX IF NOT EXISTS "Inventory_Transaction_ID"
    ON public.inventory(transaction_id);


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT "Demo Pool" FOREIGN KEY ("DemoPool")
    REFERENCES public.demopool (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "Demo Pool" ON public.inventory
    IS 'Different Demo pools for items.';

CREATE INDEX IF NOT EXISTS "Inventory_DemoPool"
    ON public.inventory("DemoPool");


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT "Product Number" FOREIGN KEY ("ProductNo")
    REFERENCES public.products ("ProductNo") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS "Inventory_ProductNo"
    ON public.inventory("ProductNo");


ALTER TABLE IF EXISTS public.products
    ADD CONSTRAINT "Category" FOREIGN KEY ("Category")
    REFERENCES public.category (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "Category" ON public.products
    IS 'Product Category';

CREATE INDEX IF NOT EXISTS "fki_Category"
    ON public.products("Category");


ALTER TABLE IF EXISTS public.reverzi
    ADD CONSTRAINT "Customer Details" FOREIGN KEY (customer_id)
    REFERENCES public.customer (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Customer Details"
    ON public.reverzi(customer_id);


ALTER TABLE IF EXISTS public.reverzi
    ADD CONSTRAINT "Customer Person Id" FOREIGN KEY (customer_person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Customer Person Id"
    ON public.reverzi(customer_person_id);


ALTER TABLE IF EXISTS public.reverzi
    ADD CONSTRAINT "Employee Id" FOREIGN KEY (person_id)
    REFERENCES public.person (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "fki_Employee Id"
    ON public.reverzi(person_id);


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Inventory Item" FOREIGN KEY (inventory_id)
    REFERENCES public.inventory (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

COMMENT ON CONSTRAINT "Inventory Item" ON public.transactions
    IS 'Loaned item from inventory';

CREATE INDEX IF NOT EXISTS "fki_Inventory Item"
    ON public.transactions(inventory_id);


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT "Reverz Header Id" FOREIGN KEY (reverz_id)
    REFERENCES public.reverzi (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "Transaction_Reverz_ID"
    ON public.transactions(reverz_id);

END;